//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoCliente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public decimal ruc { get; set; }
        public string razonSocial { get; set; }
        public string enviar { get; set; }
        public string conCopia { get; set; }
        public decimal dias { get; set; }
        public string agregarGlosa { get; set; }
        public string observaciones { get; set; }
    }
}
